alter table public.events
  add column if not exists recurring_weekly boolean not null default false,
  add column if not exists recurrence_weekday smallint not null default 4,
  add column if not exists recurrence_until date;

alter table public.events drop constraint if exists events_recurrence_weekday_check;
alter table public.events add constraint events_recurrence_weekday_check check (recurrence_weekday between 0 and 6);

alter table public.events drop constraint if exists events_status_check;
alter table public.events add constraint events_status_check check (status = any (array['draft'::text,'scheduled'::text,'live'::text,'postponed'::text,'completed'::text,'cancelled'::text]));

alter table public.announcements add column if not exists featured boolean not null default false;

create table if not exists public.change_history (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete set null,
  actor_email text,
  action text not null,
  entity_type text not null,
  entity_id text,
  summary text not null,
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

alter table public.change_history enable row level security;
grant select, insert on public.change_history to authenticated;
grant usage, select on sequence public.change_history_id_seq to authenticated;

drop policy if exists "team can read change history" on public.change_history;
create policy "team can read change history" on public.change_history for select to authenticated using (app_private.is_team_member());

drop policy if exists "team can create change history" on public.change_history;
create policy "team can create change history" on public.change_history for insert to authenticated with check (app_private.is_team_member() and (user_id is null or user_id = auth.uid()));
