alter table public.events add column if not exists locked_weekly boolean not null default false;
alter table public.events add column if not exists cover_storage_path text;
alter table public.events add column if not exists emergency_mode boolean not null default false;
alter table public.events add column if not exists emergency_message text not null default '';

create table if not exists public.admin_backups (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete set null,
  actor_email text,
  entity_type text not null,
  entity_id text,
  operation text not null check (operation in ('update','delete','create')),
  snapshot jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

alter table public.admin_backups enable row level security;
grant select, insert, delete on public.admin_backups to authenticated;
grant usage, select on sequence public.admin_backups_id_seq to authenticated;

drop policy if exists "team can read admin backups" on public.admin_backups;
create policy "team can read admin backups" on public.admin_backups for select to authenticated using (app_private.is_team_member());
drop policy if exists "team can create admin backups" on public.admin_backups;
create policy "team can create admin backups" on public.admin_backups for insert to authenticated with check (app_private.is_team_member());
drop policy if exists "team can delete admin backups" on public.admin_backups;
create policy "team can delete admin backups" on public.admin_backups for delete to authenticated using (app_private.is_team_member());

alter table public.change_history add column if not exists backup_id bigint references public.admin_backups(id) on delete set null;
alter table public.change_history add column if not exists undone_at timestamptz;
alter table public.change_history add column if not exists undone_by uuid references auth.users(id) on delete set null;

with candidate as (select id from public.events order by id asc limit 1)
update public.events
set title='Encontro Baixos Fronteira',starts_at='2026-10-01 19:30:00-03'::timestamptz,ends_at='2026-10-01 22:00:00-03'::timestamptz,
location_name='Posto Buffon',location_address='Boca da Ponte',description=case when description='' then 'Encontro oficial de toda quinta-feira da Baixos Fronteira.' else description end,
status='scheduled',sound_policy='not_allowed',sound_message='Som automotivo proibido.',is_public=true,featured=true,recurring_weekly=true,recurrence_weekday=4,recurrence_until=null,locked_weekly=true,emergency_mode=false,emergency_message=''
where id=(select id from candidate);

insert into public.events (title,starts_at,ends_at,location_name,location_address,description,status,sound_policy,sound_message,is_public,featured,recurring_weekly,recurrence_weekday,recurrence_until,locked_weekly)
select 'Encontro Baixos Fronteira','2026-10-01 19:30:00-03'::timestamptz,'2026-10-01 22:00:00-03'::timestamptz,'Posto Buffon','Boca da Ponte','Encontro oficial de toda quinta-feira da Baixos Fronteira.','scheduled','not_allowed','Som automotivo proibido.',true,true,true,4,null,true
where not exists (select 1 from public.events where locked_weekly=true);
