create table if not exists public.sponsors (
  id bigint generated by default as identity primary key,
  name text not null,
  description text not null default '',
  media_storage_path text,
  media_type text not null default 'image' check (media_type = any (array['image'::text,'video'::text])),
  instagram_url text,
  instagram_handle text,
  tiktok_url text,
  tiktok_handle text,
  website_url text,
  whatsapp_url text,
  featured boolean not null default false,
  active boolean not null default true,
  sort_order integer not null default 0,
  created_by uuid references auth.users(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.sponsors enable row level security;

grant select on table public.sponsors to anon;
grant select, insert, update, delete on table public.sponsors to authenticated;
grant select, usage on sequence public.sponsors_id_seq to authenticated;

create policy "public can read active sponsors"
on public.sponsors for select to anon
using (active = true);

create policy "authenticated can read sponsors"
on public.sponsors for select to authenticated
using (active = true or app_private.is_team_member());

create policy "team can create sponsors"
on public.sponsors for insert to authenticated
with check (app_private.is_team_member());

create policy "team can update sponsors"
on public.sponsors for update to authenticated
using (app_private.is_team_member())
with check (app_private.is_team_member());

create policy "team can delete sponsors"
on public.sponsors for delete to authenticated
using (app_private.is_team_member());

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'sponsor-media',
  'sponsor-media',
  true,
  52428800,
  array['image/jpeg','image/png','image/webp','image/gif','video/mp4','video/webm','video/quicktime']::text[]
)
on conflict (id) do update set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

create policy "team can upload sponsor media"
on storage.objects for insert to authenticated
with check (bucket_id = 'sponsor-media' and app_private.is_team_member());

create policy "team can update sponsor media"
on storage.objects for update to authenticated
using (bucket_id = 'sponsor-media' and app_private.is_team_member())
with check (bucket_id = 'sponsor-media' and app_private.is_team_member());

create policy "team can delete sponsor media"
on storage.objects for delete to authenticated
using (bucket_id = 'sponsor-media' and app_private.is_team_member());

create policy "team can list sponsor media"
on storage.objects for select to authenticated
using (bucket_id = 'sponsor-media' and app_private.is_team_member());

do $$
begin
  if exists (select 1 from pg_publication where pubname = 'supabase_realtime')
     and not exists (
       select 1 from pg_publication_tables
       where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'sponsors'
     ) then
    alter publication supabase_realtime add table public.sponsors;
  end if;
end $$;
