-- V10 final: analytics, patrocinadores por encontro e galeria com vídeo

alter table public.events
  add column if not exists sponsor_ids bigint[] not null default '{}'::bigint[];

alter table public.gallery_items
  add column if not exists media_type text not null default 'image';

do $$
begin
  if not exists (
    select 1 from pg_constraint where conname = 'gallery_items_media_type_check'
  ) then
    alter table public.gallery_items
      add constraint gallery_items_media_type_check
      check (media_type = any (array['image'::text, 'video'::text]));
  end if;
end $$;

create table if not exists public.site_analytics (
  id bigint generated by default as identity primary key,
  visitor_id text,
  event_type text not null,
  target_type text,
  target_id text,
  path text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

alter table public.site_analytics enable row level security;

grant insert on table public.site_analytics to anon, authenticated;
grant select on table public.site_analytics to authenticated;
grant select, usage on sequence public.site_analytics_id_seq to anon, authenticated;

create policy "public can insert analytics"
on public.site_analytics for insert to anon, authenticated
with check (
  char_length(coalesce(event_type, '')) between 1 and 80
  and char_length(coalesce(target_type, '')) <= 80
  and char_length(coalesce(target_id, '')) <= 180
  and char_length(coalesce(path, '')) <= 500
);

create policy "team can read analytics"
on public.site_analytics for select to authenticated
using (app_private.is_team_member());

create index if not exists site_analytics_created_at_idx on public.site_analytics(created_at desc);
create index if not exists site_analytics_event_type_idx on public.site_analytics(event_type, created_at desc);
create index if not exists site_analytics_target_idx on public.site_analytics(target_type, target_id, created_at desc);

update storage.buckets
set public = true,
    file_size_limit = greatest(coalesce(file_size_limit, 0), 52428800),
    allowed_mime_types = array['image/jpeg','image/png','image/webp','image/gif','video/mp4','video/webm','video/quicktime']::text[]
where id = 'gallery';
